language: ruby
rvm:
        - 2.1.3
addons:
        postgresql: "9.3"
before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - cp config/database.yml.travis config/database.yml
notifications:
    email:
        recipients:
            - lab@ciudadanointeligente.org
        on_success: change
        on_failure: always
