require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SolutionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Solution. As you add validations to Solution, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {title: "a title", description: "a description"}
  }

  let(:invalid_attributes) {
    {title: "", description: ""}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SolutionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before(:each) do
    @real_problem = create(:real_problem)
    @policy_problem = create(:policy_problem)
    @solution = create(:solution)
    @policy_problem.solutions.append @solution
    @real_problem.policy_problems.append @policy_problem
    @policy_problem.save
    @real_problem.save
  end

  describe "GET index" do
    it "assigns all solutions of a policy_problem as @solutions" do
      create(:solution)
      get :index, {real_problem_id: @real_problem, policy_problem_id: @policy_problem}, valid_session
      expect(assigns(:solutions)).to eq([@solution])
    end
  end

  describe "GET show" do
    it "assigns the requested solution as @solution" do
      get :show, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution}, valid_session
      expect(assigns(:solution)).to eq(@solution)
    end
  end

  describe "GET new" do
    it "assigns a new solution as @solution" do
      get :new, {real_problem_id: @real_problem, policy_problem_id: @policy_problem}, valid_session
      expect(assigns(:solution)).to be_a_new(Solution)
    end
  end

  describe "GET edit" do
    it "assigns the requested solution as @solution" do
      get :edit, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution}, valid_session
      expect(assigns(:solution)).to eq(@solution)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Solution" do
        expect {
          post :create, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, solution: attributes_for(:solution)}, valid_session
        }.to change(Solution, :count).by(1)
      end

      it "assigns a newly created solution as @solution" do
        post :create, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, solution: attributes_for(:solution)}, valid_session
        expect(assigns(:solution)).to be_a(Solution)
        expect(assigns(:solution)).to be_persisted
      end

      it "redirects to the created solution" do
        post :create, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, solution: attributes_for(:solution)}, valid_session
        expect(response).to redirect_to real_problem_policy_problem_solution_path(@real_problem, @policy_problem, Solution.last)
      end

      it "links solution to a policy_problem" do
        expect{
          post :create, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, solution: attributes_for(:solution)}, valid_session
        }.to change(@policy_problem.solutions, :count).by(1)
        expect(assigns(:solution).policy_problem_id).to eq(@policy_problem.id)
      end

      describe "with create_ww" do
        before(:each) do
          @real_problem = create(:real_problem)
          @policy_problem = create(:policy_problem)
          @policy_solution = create(:solution)

          @policy_problem.solutions.append @policy_solution
          @real_problem.policy_problems.append @policy_problem
          @real_problem.save
        end
        it "creates a new Solution" do
          expect {
            post :create_ww, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, solution: attributes_for(:solution)}, valid_session
          }.to change(Solution, :count).by(1)
        end

        it "creates a solution related to a policy problem" do
          post :create_ww, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, solution: attributes_for(:solution)}, valid_session
          expect(@policy_problem.solutions).to include(assigns(:solution))
          expect(assigns(:solution).policy_problem).to eq(@policy_problem)

          #un pp contenga un array de soluciones
          #una soluciones contenga un array de pp
          #expect(@policy_problem.solutions).to include(assigns(:solution))
          #expect(assigns(:solution).policy_problems).to include(@policy_problem)
        end

        # it "redirects to step1_3" do
        #   post :create_ww, {real_problem}
        # end
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved solution as @solution" do
        post :create, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, solution: attributes_for(:invalid_solution)}, valid_session
        expect(assigns(:solution)).to be_a_new(Solution)
      end

      it "re-renders the 'new' template" do
        post :create, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, solution: attributes_for(:invalid_solution)}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do

      it "updates the requested solution" do
        put :update, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution, solution: attributes_for(:edit_solution)}, valid_session
        @solution.reload
        expect(assigns(:solution).attributes).to include(attributes_for(:edit_solution).stringify_keys)
      end

      it "assigns the requested solution as @solution" do
        put :update, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution, solution: attributes_for(:edit_solution)}, valid_session
        expect(assigns(:solution)).to eq(@solution)
      end

      it "redirects to the solution" do
        put :update, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution, solution: attributes_for(:edit_solution)}, valid_session
        expect(response).to redirect_to real_problem_policy_problem_solution_path(@real_problem, @policy_problem, @solution)
      end
    end

    describe "with invalid params" do
      it "assigns the solution as @solution" do
        put :update, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution, solution: attributes_for(:invalid_solution)}, valid_session
        expect(assigns(:solution)).to eq(@solution)
      end

      it "re-renders the 'edit' template" do
        put :update, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution, solution: attributes_for(:invalid_solution)}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested solution" do
      expect {
        delete :destroy, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution}, valid_session
      }.to change(Solution, :count).by(-1)
    end

    it "redirects to the solutions list within a policy_problem" do
      delete :destroy, {real_problem_id: @real_problem, policy_problem_id: @policy_problem, id: @solution}, valid_session
      expect(response).to redirect_to real_problem_policy_problem_url(@real_problem, @policy_problem)
    end
  end

end
